export const SAVE_PROD_SUCCESS = 'SAVE_PROD_SUCCESS'
export const UPDATE_PROD_SUCCESS = 'UPDATE_PROD_SUCCESS'

export const LOAD_PROD_FORM = 'LOAD_PROD_FORM'
export const USER_PRODUCTS = 'USER_PRODUCTS'